update: docs
outsoarph/playbook pull request #14
Opened 2024-03-14 08:43 UTC by Arrivas

- added: tutorial
- added: aws lightsail tutorial
- added: commands
- added: bash/vim commands WIP
- edit: removed extra items on navbar

2024-03-18 06:28 UTC, Keanu-Tibule approved these changes
Slight formatting error, grammatical errors and missing content, but overall, it looks great.

2024-03-18 06:28 UTC, Keanu-Tibule commented on docs/guide/tutorial/aws/add-cdn-lightsail.md
> +        - ![Screenshot cname dist](./img/test-cloudfront.png)
Formatting Error. Extra indentation caused the lists and sublists to display incorrectly. Subtract an indent from the selected lines.

2024-03-18 06:28 UTC, Keanu-Tibule commented on docs/guide/tutorial/aws/add-cdn-lightsail.md
> +    3. Now add your origin domain, and www then click `Create Certificate`. *example*:
Example content missing.

2024-03-18 10:22 UTC, ashcslmn requested changes

2024-03-18 10:22 UTC, ashcslmn commented on package-lock.json
this should not be committed if no changes in package.json

2024-03-22 15:58 UTC, ashcslmn approved these changes

2024-03-22 15:59 UTC, merged